// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_label_battery;
lv_obj_t *uic_clear;
lv_obj_t *uic_noise3;
lv_obj_t *uic_noise2;
lv_obj_t *uic_noise1;
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Noise1;
lv_obj_t *ui_Noise2;
lv_obj_t *ui_Noise3;
lv_obj_t *ui_Clear;
lv_obj_t *ui_Label3;

// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Noise1 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Noise1, &ui_img_noise1_png);
lv_obj_set_width( ui_Noise1, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Noise1, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Noise1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Noise1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Noise1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Noise1,2700);

ui_Noise2 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Noise2, &ui_img_noise2_png);
lv_obj_set_width( ui_Noise2, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Noise2, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Noise2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Noise2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Noise2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Noise2,2700);

ui_Noise3 = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Noise3, &ui_img_noise3_png);
lv_obj_set_width( ui_Noise3, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Noise3, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Noise3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Noise3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Noise3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Noise3,2700);

ui_Clear = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Clear, &ui_img_clear_png);
lv_obj_set_width( ui_Clear, LV_SIZE_CONTENT);  /// 280
lv_obj_set_height( ui_Clear, LV_SIZE_CONTENT);   /// 240
lv_obj_set_align( ui_Clear, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Clear, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Clear, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Clear,2700);

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -16 );
lv_obj_set_y( ui_Label3, 0 );
lv_obj_set_align( ui_Label3, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_Label3,"0.00v");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_noise1 = ui_Noise1;
uic_noise2 = ui_Noise2;
uic_noise3 = ui_Noise3;
uic_clear = ui_Clear;
uic_label_battery = ui_Label3;

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
uic_noise1= NULL;
ui_Noise1= NULL;
uic_noise2= NULL;
ui_Noise2= NULL;
uic_noise3= NULL;
ui_Noise3= NULL;
uic_clear= NULL;
ui_Clear= NULL;
uic_label_battery= NULL;
ui_Label3= NULL;

}
