// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Noise1;
extern lv_obj_t *ui_Noise2;
extern lv_obj_t *ui_Noise3;
extern lv_obj_t *ui_Clear;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t *uic_noise1;
extern lv_obj_t *uic_noise2;
extern lv_obj_t *uic_noise3;
extern lv_obj_t *uic_clear;
extern lv_obj_t *uic_label_battery;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

